### PR TITLE
Getting first & last name from email if needed

### PR DESCRIPTION
**Pull request by BuckinghamAJ**
Realized that if Login.gov doesn't return a given_name or family_name I would need to pull it from the email. That is what this code addition is doing.

### CODE REVIEW

**Comment by BuckinghamAJ** [comment]
Want to get into a new pre-release for srt-api before letting Login.gov goes to production.

**Comment by gsa-bri** [comment]
Cool -checking it out now. Note that if a user prefers a different name
than what is in their email, they would have to reach out directly to us
and we'd change it in Django

**Comment by BuckinghamAJ** [comment]
Not worth doing this at the moment.

**Comment by gsa-bri** [comment]
just verified that not all agencies follow the "firstname.lastname@"
convention.

**Pull request closed without merging**
